# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-11 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='desc',
            field=models.TextField(verbose_name=''),
        ),
    ]
